name: "Build Docker Images - CI"

on:
  push:
    branches: [ actions-test ]
  pull_request:
    branches: [ main ]

jobs:

  find_docker_files:
    runs-on: ubuntu-latest
    name: "Get Docker Files list"
    outputs:
      docker_files: ${{ steps.find_docker_files.outputs.docker_files }}
    steps:
    - uses: actions/checkout@v3
    - id: get-changed-docker-files
      name: "Get Docker Files"
      run: |
        DOCKER_FILES="[$(find . -iname Dockerfile | sed 's/.*/"&"/' | paste -d, -s)]"
        echo "DOCKER_FILES: $DOCKER_FILES"
        echo echo "::set-output name=docker_files::$DOCKER_FILES"