name: Build Docker Images - CI

on:
  push:
    branches: [ actions-test ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker images changed
      run: |
        echo "Hello"