name: "Build Docker Images - CI"

on:
  push:
    branches: [ actions-test ]
  pull_request:
    branches: [ main ]

jobs:

  find_docker_files:
    runs-on: ubuntu-latest
    name: "Get Docker Files list"
    outputs:
      docker_files: ${{ steps.find_docker_files.outputs.docker_files }}
    steps:
      -
        id: git-checkout
        name: "Checkout files from GIT"
        uses: actions/checkout@v3
      -
        id: get-docker-files
        name: "Get Docker files list"
        run: |
          CHANGED_FILES="[$(find {{ github.workspace }} -iname Dockerfile | sed 's/.*/"&"/' | paste -d, -s)]"
          echo ::set-output name=docker_files::$CHANGED_FILES