name: "Build Docker Images - CI"

on:
  push:
    branches: [ actions-test ]
  pull_request:
    branches: [ main ]

jobs:

  find_docker_files:
    runs-on: ubuntu-latest
    name: "Get Docker Files list"
    outputs:
      docker_files: ${{ steps.find_docker_files.outputs.docker_files }}
    steps:
      -
        id: git-checkout
        name: "Checkut files from GIT"
        uses: actions/checkout@v3