name: Build Docker Images - CI

on:
  push:
    branches: [ actions-test ]
  pull_request:
    branches: [ main ]

jobs:

  find_docker_files:

    runs-on: ubuntu-latest

    name: "Get changed Docker Files list"

    steps:    
    - uses: actions/checkout@v3
    - id: get-changed-docker-files
      run: |
        echo "Hello"