name: "Build Docker Images - CI"

on:
  push:
    branches: [ actions-test ]
  pull_request:
    branches: [ main ]

jobs:

  find_docker_files:
    runs-on: ubuntu-latest
    name: "Get Docker Files list"
    outputs:
      docker_files: ${{ steps.get-docker-files.outputs.docker_files }}
    steps:
      -
        id: git-checkout
        name: "Checkout files from GIT"
        uses: actions/checkout@v3
      -
        id: get-docker-files
        name: "Get Docker files list"
        run: |
          DOCKER_FILES="[$(find ${{ github.workspace }} -iname Dockerfile | sed "s|${{ github.workspace }}||" | xargs dirname | sed 's/.*/"&"/' | paste -d, -s)]"
          echo "DOCKER_FILES: $DOCKER_FILES"
          echo ::set-output name=docker_files::$DOCKER_FILES

  build_and_push_images:
    runs-on: ubuntu-latest
    name: "Build and Push Docker Images to repository"
    needs: find_docker_files
    strategy:
      matrix:
        docker_file: ${{fromJSON(needs.find_docker_files.outputs.docker_files)}}
    steps:
      -
        id: setup-quemu
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        id: setup-docker-buildx
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        id: login-to-docker-repository
        name: "Login to Docker Repository"
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        id: build-and-push-images
        name: "Build and push Docker images to the registry"
        uses: docker/build-push-action@v3
        with:
          context: "${{github.workspace}}${{ matrix.docker_file }}"
        #run: |
        #  echo "Docker file: ${{ matrix.docker_file }}"