name: Build Docker Images - CI

on:
  push:
    branches: [ actions-test ]
  pull_request:
    branches: [ main ]

jobs:

  find_docker_files:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.find_docker_files.outputs.docker_files }}
    name: "Get changed Docker Files"
    steps:
      - uses: actions/checkout@v3
      id: get-changed-docker-files
      name: "Get changed Docker Files"      
      run: |
        CHANGED_FILES="[$(find {{ github.workspace }} -iname Dockerfile | sed 's/.*/"&"/' | paste -d, -s)]"
        echo ::set-output name=docker_files::$CHANGED_FILES