name: Build Docker Images - CI

on:
  push:
    branches: [ actions-test ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker images changed
      run: |
        for FILE in $(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | grep -i "Dockerfile")
        do
          TEMP_IMAGE_NAME="img-$RANDOM"
          docker build {{ github.workspace }} --file $FILE -t $TEMP_IMAGE_NAME
          if [ $? -ne 0 ] 
          then 
            echo "Error building image for: $FILE"
            exit 1
          fi
